services:
  redmine:
    image: eaudeweb/redmine:local
    build: .
    container_name: redmine
    restart: "no"
    volumes:
      - type: bind
        source: ./.data/crontab.dev
        target: /var/local/redmine/crontab
      - type: bind
        source: ./scripts/update_configuration.py
        target: /var/local/redmine/scripts/update_configuration.py
      # - ./themes:/usr/src/redmine/themes
      # - ./app:/usr/src/redmine/app
      # - ./lib:/usr/src/redmine/lib
    ports:
      - 8090:3000
    # entrypoint: ["tail", "-f", "/dev/null"]

  mysql:
    container_name: redmine_mysql

  # For external hosted SQL servers register a static DNS entry
  # extra_hosts:
  #   - "mysql:192.168.10.5"


  smtp:
    container_name: smtp
    image: eaudeweb/mailtrap
    ports:
      - "25:2525"
      - "127.0.0.1:8025:80"
    environment:
      MT_PASSWD: "changeme"
