services:

  redmine:
    image: eaudeweb/redmine:local
    build: .
    container_name: redmine
    ports:
      - 8090:3000
# For external hosted SQL servers register a static DNS entry
#    extra_hosts:
#      - "mysql:192.168.10.5"

  mysql:
    container_name: redmine_mysql

  smtp:
    container_name: smtp
    image: eaudeweb/mailtrap
    ports:
      - "25:2525"
      - "127.0.0.1:8025:80"
    environment:
      MT_PASSWD: "changeme"
